### ISSUE TITLE
chines

### ISSUE THREAD

**Issue by kuisike** [ka-dyn/ExpandedContent#115]
Will the latest updates add Chinese?thank you

**Comment by bittercranberry** [comment]
Only if someone who is fluent can help.
Many mods have some Mandarin Chinese support as about a year ago 2 or 3 people who spoke it where translating mods for people and modders could put the text in the localisation file, but they are not translating anymore so new content is currently only in English.

**Comment by nixgnot** [comment]
> Only if someone who is fluent can help. Many mods have some Mandarin Chinese support as about a year ago 2 or 3 people who spoke it where translating mods for people and modders could put the text in the localisation file, but they are not translating anymore so new content is currently only in English.

In fact we are still doing that :P
but we are using another small mod that can add chinese texts, by a external localisation files, after content mods (like yours) loaded now... which use the owlcat‘s own multi-language supporting mechanics,
that means chinese users donot need modders to imerge localisation files. That's very convenient.

**Comment by bittercranberry** [comment]
Any chance you could link me that? I would like to put a link to it in the mod description, but I would probably use the wrong link if tried to find the right page myself on a non-english site.

**Comment by nixgnot** [comment]
> Any chance you could link me that? I would like to put a link to it in the mod description, but I would probably use the wrong link if tried to find the right page myself on a non-english site.
yeah glad for that.
it's https://github.com/nixgnot/WOTR-CONTENTS-MODS-CN
thats a collection that include most mods' links (include EC), and their Chinese Localization.

the EC external Localization is already updated to newest release.

**Comment by bittercranberry** [comment]
Nice, I'll link that in the read me.
Out of curiosity, what did EC do to get the low recommendation?

**Comment by nixgnot** [comment]
> Nice, I'll link that in the read me. Out of curiosity, what did EC do to get the low recommendation?

oh lol i forget that....
sry，please dont mind that..

thats just because ancient version of EC have some conflict with other mod, and the localization of EC is not so good (machine translation) at that time
while i made that list really long ago.. then completely forgot to update that recommend list....
just remember update the localization :P

i should update that list.  please dont mind that ┗( T﹏T )┛

**Comment by bittercranberry** [comment]
That's good to hear, I was worried the Chinese players knew about bugs I didn't and that I was getting marked down for them.
Sorry if the mod has been a pain to translate, I know the deity text can get a bit silly at time.

If there are any bugs being reported on your version of the mod, (or requests for new content), please forward them here. I would hate if bugs were not being fixed just because I couldn't read the report.
