### ISSUE TITLE
Game will not load

### ISSUE THREAD

**Issue by jdgen11** [ka-dyn/ExpandedContent#18]
Hello, thanks for a wonderful mod.
I recently started playing again after about 4 or 5 months. I remember having this mod before and it working just fine. Now when I load the game it freezes at the loading window. All my other mods run fine. Other mods being; Buy Material Components, Damage Breakdown, Enhanced Content, Respec Mod, Toy Box, Visual Adjustments, Weapon Focus Plus and World Crawl. Please let me know if you have any ideas why it won't run.
Thanks

**Comment by bittercranberry** [comment]
Hello, could you please send me the error log made by the UMM so I can have a look?
Also running the mod by itself to see if it is a compatibility issue with another mod would be a great help.

**Comment by jdgen11** [comment]
Thanks for your quick response. I went ahead and Uninstalled all other mods
except Expanded Contender. Then loaded the game. It loaded just fine. So I
installed each mod one by one loading the game after each seeing if one of
the mods had a bad interaction. Nope. All my mods are loaded now. Strange,
is there a reason that I may have needed to install Expanded Content first?
Well thanks for your help and great mod.

**Comment by FrijDom** [comment]
Well, I'm not sure why reinstalling them changed it, but I suspect you're running into the same problem a lot of people have been with Worldcrawl combined with other content mods. It loads just fine, but it takes some time to initialize, during which time it 'freezes' because it doesn't send any information back to the computer.
