### ISSUE TITLE
Living Scripture balance suggestions

### ISSUE THREAD

**Issue by Redicular** [ka-dyn/ExpandedContent#5]
I'm well aware that living scripture is a user requested feature and thus may be immune to balance adjustments but I would still like to put my  suggestions down in an official format just to have them thought about.

my problem with the balance of Living Scripture is not so much how it compares to other Inquisitors, but more so how it compares to cleric.
The current comparison between the two basically comes down to:
trading channel energy and a domain slot
for
6 caster feats (2 focus, spell specialization, and 3 of choice)
6 teamwork feats
bane and stalwart

My suggestions:
1st:  instead of base cleric spell book, it use the angel-fire apostle version of the cleric spell-book which has 1 less slot per level
2nd:  limit domain access:  either to just knowledge domain, or a subset of knowledge, rune, magic, and artifice
3rd:  the bonus wizard feats at 10+ are removed entirely
4th: in concert with the above - the spell focus feat is moved to 4, the spell resistance is moved to 7, the spell specialization is moved to 10, and the greater focus is moved to 14
5th:  1/2 the teamwork feats are removed(6+12+18 or 3+9+15) I'd vote for 3+9+15

as mentioned, I will completely understand if your response is: "my requestor is happy and that's all that matters"  but i find the concept behind the class extremely interesting.  blurring the lines between inquisitor and cleric is a good idea.
Just don't replace cleric entirely

**Comment by Mythalar** [comment]
Hey there, I guesse I'll use this thread and not create one another ^^

I don't have anything to say over balance since the different classes are not really balanced after all.

But a question and possibly suggestion :
Reading the description I would have guessed a intelligence based archetype (like the Living grimoire inquisitor archetype and some other thing from D&D3 or 3.5 I cannot recall) but it seems to be wisdom based still.
Is it actually correct andor could we have an option to change this in the setting file? (Truinto did this in the Darkcodex mod for the psychokineticist).

**Comment by FrijDom** [comment]
Hi! I have answers for this from the tabletop: Living Scripture is actually meant to use the Warpriest spell slots per day, as well as having Sacred Weapon (using their book as their only weapon), and using intelligence. It was never supposed to get domains, higher level casting, etc.

**Comment by Mythalar** [comment]
You are perfectly right I know this.
Since it's already kind of a homebrew thing as of now I guess some INT variation could bring diversity nonetheless :)
Domain powers could still rely on wisdom to make the archetype quite MAD, same as the arcanist class.
