### ISSUE TITLE
2nd Favored Terrain For Drake Warden

### ISSUE THREAD

**Issue by Ballagarraidh** [ka-dyn/ExpandedContent#98]
Upon reaching 8 levels in the Drake Warden archetype of the Ranger, I am asked to pick a 2nd Favored Terrain, however, all the choices are redded out because of a prerequisite requirement I cannot fulfill.

For further specifics, I picked Abyss as my initial favored terrain.

**Comment by bittercranberry** [comment]
Ah I see what's happened, looks like a rank-up selection now needs a base one before it, I'll have to edit the order you get things a wee bit so instead of halving the amount gained on 2 different levels I'll take away the lvl8 option and restore the later options.
The next update will fix this but you might need to respec the Drake Warden.
I will leave this ticket open until the update, thanks for finding this.
